//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  /** Internal type. DO NOT USE DIRECTLY. */
type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
/** Internal type. DO NOT USE DIRECTLY. */
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  pages: Pages;
  pagesConnection: PagesConnection;
  posts: Posts;
  postsConnection: PostsConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPagesArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPagesConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PagesFilter>;
};


export type QueryPostsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPostsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PostsFilter>;
};

export type DocumentFilter = {
  pages?: InputMaybe<PagesFilter>;
  posts?: InputMaybe<PostsFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Pages | Posts | Folder;

export type PagesSectionsProse = {
  __typename?: 'PagesSectionsProse';
  body?: Maybe<Scalars['String']['output']>;
};

export type PagesSectionsDisclosure = {
  __typename?: 'PagesSectionsDisclosure';
  summary?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['String']['output']>;
};

export type PagesSectionsEmbed = {
  __typename?: 'PagesSectionsEmbed';
  src?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  variant?: Maybe<Scalars['String']['output']>;
  fallback?: Maybe<Scalars['String']['output']>;
};

export type PagesSectionsCard = {
  __typename?: 'PagesSectionsCard';
  heading?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  imageAlt?: Maybe<Scalars['String']['output']>;
  href?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['String']['output']>;
};

export type PagesSectionsGalleryImages = {
  __typename?: 'PagesSectionsGalleryImages';
  src?: Maybe<Scalars['String']['output']>;
  alt?: Maybe<Scalars['String']['output']>;
};

export type PagesSectionsGallery = {
  __typename?: 'PagesSectionsGallery';
  images?: Maybe<Array<Maybe<PagesSectionsGalleryImages>>>;
};

export type PagesSectionsProfilesPeopleLinks = {
  __typename?: 'PagesSectionsProfilesPeopleLinks';
  href?: Maybe<Scalars['String']['output']>;
};

export type PagesSectionsProfilesPeople = {
  __typename?: 'PagesSectionsProfilesPeople';
  name?: Maybe<Scalars['String']['output']>;
  role?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['String']['output']>;
  links?: Maybe<Array<Maybe<PagesSectionsProfilesPeopleLinks>>>;
};

export type PagesSectionsProfiles = {
  __typename?: 'PagesSectionsProfiles';
  people?: Maybe<Array<Maybe<PagesSectionsProfilesPeople>>>;
};

export type PagesSectionsVideo = {
  __typename?: 'PagesSectionsVideo';
  src?: Maybe<Scalars['String']['output']>;
  captions?: Maybe<Scalars['String']['output']>;
  poster?: Maybe<Scalars['String']['output']>;
  caption?: Maybe<Scalars['String']['output']>;
};

export type PagesSectionsButtonsButtons = {
  __typename?: 'PagesSectionsButtonsButtons';
  label?: Maybe<Scalars['String']['output']>;
  href?: Maybe<Scalars['String']['output']>;
  style?: Maybe<Scalars['String']['output']>;
  newTab?: Maybe<Scalars['Boolean']['output']>;
};

export type PagesSectionsButtons = {
  __typename?: 'PagesSectionsButtons';
  buttons?: Maybe<Array<Maybe<PagesSectionsButtonsButtons>>>;
};

export type PagesSectionsColumnsColumns = {
  __typename?: 'PagesSectionsColumnsColumns';
  body?: Maybe<Scalars['String']['output']>;
};

export type PagesSectionsColumns = {
  __typename?: 'PagesSectionsColumns';
  layout?: Maybe<Scalars['String']['output']>;
  columns?: Maybe<Array<Maybe<PagesSectionsColumnsColumns>>>;
};

export type PagesSectionsImage = {
  __typename?: 'PagesSectionsImage';
  src?: Maybe<Scalars['String']['output']>;
  alt?: Maybe<Scalars['String']['output']>;
  decorative?: Maybe<Scalars['Boolean']['output']>;
  caption?: Maybe<Scalars['String']['output']>;
  width?: Maybe<Scalars['Float']['output']>;
  height?: Maybe<Scalars['Float']['output']>;
};

export type PagesSectionsQuote = {
  __typename?: 'PagesSectionsQuote';
  text?: Maybe<Scalars['String']['output']>;
  attribution?: Maybe<Scalars['String']['output']>;
};

export type PagesSectionsFormFields = {
  __typename?: 'PagesSectionsFormFields';
  label?: Maybe<Scalars['String']['output']>;
  name?: Maybe<Scalars['String']['output']>;
  type?: Maybe<Scalars['String']['output']>;
  required?: Maybe<Scalars['Boolean']['output']>;
  help?: Maybe<Scalars['String']['output']>;
};

export type PagesSectionsForm = {
  __typename?: 'PagesSectionsForm';
  name?: Maybe<Scalars['String']['output']>;
  intro?: Maybe<Scalars['String']['output']>;
  fields?: Maybe<Array<Maybe<PagesSectionsFormFields>>>;
  consent?: Maybe<Scalars['String']['output']>;
  success?: Maybe<Scalars['String']['output']>;
  submit?: Maybe<Scalars['String']['output']>;
  action?: Maybe<Scalars['String']['output']>;
};

export type PagesSectionsHtml = {
  __typename?: 'PagesSectionsHtml';
  html?: Maybe<Scalars['String']['output']>;
};

export type PagesSections = PagesSectionsProse | PagesSectionsDisclosure | PagesSectionsEmbed | PagesSectionsCard | PagesSectionsGallery | PagesSectionsProfiles | PagesSectionsVideo | PagesSectionsButtons | PagesSectionsColumns | PagesSectionsImage | PagesSectionsQuote | PagesSectionsForm | PagesSectionsHtml;

export type Pages = Node & Document & {
  __typename?: 'Pages';
  title?: Maybe<Scalars['String']['output']>;
  excerpt?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  imageAlt?: Maybe<Scalars['String']['output']>;
  sections?: Maybe<Array<Maybe<PagesSections>>>;
  url?: Maybe<Scalars['String']['output']>;
  parent?: Maybe<Scalars['String']['output']>;
  order?: Maybe<Scalars['Float']['output']>;
  date?: Maybe<Scalars['String']['output']>;
  modified?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type PagesSectionsProseFilter = {
  body?: InputMaybe<StringFilter>;
};

export type PagesSectionsDisclosureFilter = {
  summary?: InputMaybe<StringFilter>;
  body?: InputMaybe<StringFilter>;
};

export type PagesSectionsEmbedFilter = {
  src?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  variant?: InputMaybe<StringFilter>;
  fallback?: InputMaybe<StringFilter>;
};

export type PagesSectionsCardFilter = {
  heading?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  imageAlt?: InputMaybe<StringFilter>;
  href?: InputMaybe<StringFilter>;
  body?: InputMaybe<StringFilter>;
};

export type PagesSectionsGalleryImagesFilter = {
  src?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
};

export type PagesSectionsGalleryFilter = {
  images?: InputMaybe<PagesSectionsGalleryImagesFilter>;
};

export type PagesSectionsProfilesPeopleLinksFilter = {
  href?: InputMaybe<StringFilter>;
};

export type PagesSectionsProfilesPeopleFilter = {
  name?: InputMaybe<StringFilter>;
  role?: InputMaybe<StringFilter>;
  body?: InputMaybe<StringFilter>;
  links?: InputMaybe<PagesSectionsProfilesPeopleLinksFilter>;
};

export type PagesSectionsProfilesFilter = {
  people?: InputMaybe<PagesSectionsProfilesPeopleFilter>;
};

export type PagesSectionsVideoFilter = {
  src?: InputMaybe<ImageFilter>;
  captions?: InputMaybe<ImageFilter>;
  poster?: InputMaybe<ImageFilter>;
  caption?: InputMaybe<StringFilter>;
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type PagesSectionsButtonsButtonsFilter = {
  label?: InputMaybe<StringFilter>;
  href?: InputMaybe<StringFilter>;
  style?: InputMaybe<StringFilter>;
  newTab?: InputMaybe<BooleanFilter>;
};

export type PagesSectionsButtonsFilter = {
  buttons?: InputMaybe<PagesSectionsButtonsButtonsFilter>;
};

export type PagesSectionsColumnsColumnsFilter = {
  body?: InputMaybe<StringFilter>;
};

export type PagesSectionsColumnsFilter = {
  layout?: InputMaybe<StringFilter>;
  columns?: InputMaybe<PagesSectionsColumnsColumnsFilter>;
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type PagesSectionsImageFilter = {
  src?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
  decorative?: InputMaybe<BooleanFilter>;
  caption?: InputMaybe<StringFilter>;
  width?: InputMaybe<NumberFilter>;
  height?: InputMaybe<NumberFilter>;
};

export type PagesSectionsQuoteFilter = {
  text?: InputMaybe<StringFilter>;
  attribution?: InputMaybe<StringFilter>;
};

export type PagesSectionsFormFieldsFilter = {
  label?: InputMaybe<StringFilter>;
  name?: InputMaybe<StringFilter>;
  type?: InputMaybe<StringFilter>;
  required?: InputMaybe<BooleanFilter>;
  help?: InputMaybe<StringFilter>;
};

export type PagesSectionsFormFilter = {
  name?: InputMaybe<StringFilter>;
  intro?: InputMaybe<StringFilter>;
  fields?: InputMaybe<PagesSectionsFormFieldsFilter>;
  consent?: InputMaybe<StringFilter>;
  success?: InputMaybe<StringFilter>;
  submit?: InputMaybe<StringFilter>;
  action?: InputMaybe<StringFilter>;
};

export type PagesSectionsHtmlFilter = {
  html?: InputMaybe<StringFilter>;
};

export type PagesSectionsFilter = {
  prose?: InputMaybe<PagesSectionsProseFilter>;
  disclosure?: InputMaybe<PagesSectionsDisclosureFilter>;
  embed?: InputMaybe<PagesSectionsEmbedFilter>;
  card?: InputMaybe<PagesSectionsCardFilter>;
  gallery?: InputMaybe<PagesSectionsGalleryFilter>;
  profiles?: InputMaybe<PagesSectionsProfilesFilter>;
  video?: InputMaybe<PagesSectionsVideoFilter>;
  buttons?: InputMaybe<PagesSectionsButtonsFilter>;
  columns?: InputMaybe<PagesSectionsColumnsFilter>;
  image?: InputMaybe<PagesSectionsImageFilter>;
  quote?: InputMaybe<PagesSectionsQuoteFilter>;
  form?: InputMaybe<PagesSectionsFormFilter>;
  html?: InputMaybe<PagesSectionsHtmlFilter>;
};

export type DatetimeFilter = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type PagesFilter = {
  title?: InputMaybe<StringFilter>;
  excerpt?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  imageAlt?: InputMaybe<StringFilter>;
  sections?: InputMaybe<PagesSectionsFilter>;
  url?: InputMaybe<StringFilter>;
  parent?: InputMaybe<StringFilter>;
  order?: InputMaybe<NumberFilter>;
  date?: InputMaybe<DatetimeFilter>;
  modified?: InputMaybe<DatetimeFilter>;
};

export type PagesConnectionEdges = {
  __typename?: 'PagesConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Pages>;
};

export type PagesConnection = Connection & {
  __typename?: 'PagesConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PagesConnectionEdges>>>;
};

export type PostsSectionsProse = {
  __typename?: 'PostsSectionsProse';
  body?: Maybe<Scalars['String']['output']>;
};

export type PostsSectionsDisclosure = {
  __typename?: 'PostsSectionsDisclosure';
  summary?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['String']['output']>;
};

export type PostsSectionsEmbed = {
  __typename?: 'PostsSectionsEmbed';
  src?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  variant?: Maybe<Scalars['String']['output']>;
  fallback?: Maybe<Scalars['String']['output']>;
};

export type PostsSectionsCard = {
  __typename?: 'PostsSectionsCard';
  heading?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  imageAlt?: Maybe<Scalars['String']['output']>;
  href?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['String']['output']>;
};

export type PostsSectionsGalleryImages = {
  __typename?: 'PostsSectionsGalleryImages';
  src?: Maybe<Scalars['String']['output']>;
  alt?: Maybe<Scalars['String']['output']>;
};

export type PostsSectionsGallery = {
  __typename?: 'PostsSectionsGallery';
  images?: Maybe<Array<Maybe<PostsSectionsGalleryImages>>>;
};

export type PostsSectionsProfilesPeopleLinks = {
  __typename?: 'PostsSectionsProfilesPeopleLinks';
  href?: Maybe<Scalars['String']['output']>;
};

export type PostsSectionsProfilesPeople = {
  __typename?: 'PostsSectionsProfilesPeople';
  name?: Maybe<Scalars['String']['output']>;
  role?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['String']['output']>;
  links?: Maybe<Array<Maybe<PostsSectionsProfilesPeopleLinks>>>;
};

export type PostsSectionsProfiles = {
  __typename?: 'PostsSectionsProfiles';
  people?: Maybe<Array<Maybe<PostsSectionsProfilesPeople>>>;
};

export type PostsSectionsVideo = {
  __typename?: 'PostsSectionsVideo';
  src?: Maybe<Scalars['String']['output']>;
  captions?: Maybe<Scalars['String']['output']>;
  poster?: Maybe<Scalars['String']['output']>;
  caption?: Maybe<Scalars['String']['output']>;
};

export type PostsSectionsButtonsButtons = {
  __typename?: 'PostsSectionsButtonsButtons';
  label?: Maybe<Scalars['String']['output']>;
  href?: Maybe<Scalars['String']['output']>;
  style?: Maybe<Scalars['String']['output']>;
  newTab?: Maybe<Scalars['Boolean']['output']>;
};

export type PostsSectionsButtons = {
  __typename?: 'PostsSectionsButtons';
  buttons?: Maybe<Array<Maybe<PostsSectionsButtonsButtons>>>;
};

export type PostsSectionsColumnsColumns = {
  __typename?: 'PostsSectionsColumnsColumns';
  body?: Maybe<Scalars['String']['output']>;
};

export type PostsSectionsColumns = {
  __typename?: 'PostsSectionsColumns';
  layout?: Maybe<Scalars['String']['output']>;
  columns?: Maybe<Array<Maybe<PostsSectionsColumnsColumns>>>;
};

export type PostsSectionsImage = {
  __typename?: 'PostsSectionsImage';
  src?: Maybe<Scalars['String']['output']>;
  alt?: Maybe<Scalars['String']['output']>;
  decorative?: Maybe<Scalars['Boolean']['output']>;
  caption?: Maybe<Scalars['String']['output']>;
  width?: Maybe<Scalars['Float']['output']>;
  height?: Maybe<Scalars['Float']['output']>;
};

export type PostsSectionsQuote = {
  __typename?: 'PostsSectionsQuote';
  text?: Maybe<Scalars['String']['output']>;
  attribution?: Maybe<Scalars['String']['output']>;
};

export type PostsSectionsFormFields = {
  __typename?: 'PostsSectionsFormFields';
  label?: Maybe<Scalars['String']['output']>;
  name?: Maybe<Scalars['String']['output']>;
  type?: Maybe<Scalars['String']['output']>;
  required?: Maybe<Scalars['Boolean']['output']>;
  help?: Maybe<Scalars['String']['output']>;
};

export type PostsSectionsForm = {
  __typename?: 'PostsSectionsForm';
  name?: Maybe<Scalars['String']['output']>;
  intro?: Maybe<Scalars['String']['output']>;
  fields?: Maybe<Array<Maybe<PostsSectionsFormFields>>>;
  consent?: Maybe<Scalars['String']['output']>;
  success?: Maybe<Scalars['String']['output']>;
  submit?: Maybe<Scalars['String']['output']>;
  action?: Maybe<Scalars['String']['output']>;
};

export type PostsSectionsHtml = {
  __typename?: 'PostsSectionsHtml';
  html?: Maybe<Scalars['String']['output']>;
};

export type PostsSections = PostsSectionsProse | PostsSectionsDisclosure | PostsSectionsEmbed | PostsSectionsCard | PostsSectionsGallery | PostsSectionsProfiles | PostsSectionsVideo | PostsSectionsButtons | PostsSectionsColumns | PostsSectionsImage | PostsSectionsQuote | PostsSectionsForm | PostsSectionsHtml;

export type Posts = Node & Document & {
  __typename?: 'Posts';
  title?: Maybe<Scalars['String']['output']>;
  excerpt?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  imageAlt?: Maybe<Scalars['String']['output']>;
  sections?: Maybe<Array<Maybe<PostsSections>>>;
  url?: Maybe<Scalars['String']['output']>;
  date?: Maybe<Scalars['String']['output']>;
  modified?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type PostsSectionsProseFilter = {
  body?: InputMaybe<StringFilter>;
};

export type PostsSectionsDisclosureFilter = {
  summary?: InputMaybe<StringFilter>;
  body?: InputMaybe<StringFilter>;
};

export type PostsSectionsEmbedFilter = {
  src?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  variant?: InputMaybe<StringFilter>;
  fallback?: InputMaybe<StringFilter>;
};

export type PostsSectionsCardFilter = {
  heading?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  imageAlt?: InputMaybe<StringFilter>;
  href?: InputMaybe<StringFilter>;
  body?: InputMaybe<StringFilter>;
};

export type PostsSectionsGalleryImagesFilter = {
  src?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
};

export type PostsSectionsGalleryFilter = {
  images?: InputMaybe<PostsSectionsGalleryImagesFilter>;
};

export type PostsSectionsProfilesPeopleLinksFilter = {
  href?: InputMaybe<StringFilter>;
};

export type PostsSectionsProfilesPeopleFilter = {
  name?: InputMaybe<StringFilter>;
  role?: InputMaybe<StringFilter>;
  body?: InputMaybe<StringFilter>;
  links?: InputMaybe<PostsSectionsProfilesPeopleLinksFilter>;
};

export type PostsSectionsProfilesFilter = {
  people?: InputMaybe<PostsSectionsProfilesPeopleFilter>;
};

export type PostsSectionsVideoFilter = {
  src?: InputMaybe<ImageFilter>;
  captions?: InputMaybe<ImageFilter>;
  poster?: InputMaybe<ImageFilter>;
  caption?: InputMaybe<StringFilter>;
};

export type PostsSectionsButtonsButtonsFilter = {
  label?: InputMaybe<StringFilter>;
  href?: InputMaybe<StringFilter>;
  style?: InputMaybe<StringFilter>;
  newTab?: InputMaybe<BooleanFilter>;
};

export type PostsSectionsButtonsFilter = {
  buttons?: InputMaybe<PostsSectionsButtonsButtonsFilter>;
};

export type PostsSectionsColumnsColumnsFilter = {
  body?: InputMaybe<StringFilter>;
};

export type PostsSectionsColumnsFilter = {
  layout?: InputMaybe<StringFilter>;
  columns?: InputMaybe<PostsSectionsColumnsColumnsFilter>;
};

export type PostsSectionsImageFilter = {
  src?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
  decorative?: InputMaybe<BooleanFilter>;
  caption?: InputMaybe<StringFilter>;
  width?: InputMaybe<NumberFilter>;
  height?: InputMaybe<NumberFilter>;
};

export type PostsSectionsQuoteFilter = {
  text?: InputMaybe<StringFilter>;
  attribution?: InputMaybe<StringFilter>;
};

export type PostsSectionsFormFieldsFilter = {
  label?: InputMaybe<StringFilter>;
  name?: InputMaybe<StringFilter>;
  type?: InputMaybe<StringFilter>;
  required?: InputMaybe<BooleanFilter>;
  help?: InputMaybe<StringFilter>;
};

export type PostsSectionsFormFilter = {
  name?: InputMaybe<StringFilter>;
  intro?: InputMaybe<StringFilter>;
  fields?: InputMaybe<PostsSectionsFormFieldsFilter>;
  consent?: InputMaybe<StringFilter>;
  success?: InputMaybe<StringFilter>;
  submit?: InputMaybe<StringFilter>;
  action?: InputMaybe<StringFilter>;
};

export type PostsSectionsHtmlFilter = {
  html?: InputMaybe<StringFilter>;
};

export type PostsSectionsFilter = {
  prose?: InputMaybe<PostsSectionsProseFilter>;
  disclosure?: InputMaybe<PostsSectionsDisclosureFilter>;
  embed?: InputMaybe<PostsSectionsEmbedFilter>;
  card?: InputMaybe<PostsSectionsCardFilter>;
  gallery?: InputMaybe<PostsSectionsGalleryFilter>;
  profiles?: InputMaybe<PostsSectionsProfilesFilter>;
  video?: InputMaybe<PostsSectionsVideoFilter>;
  buttons?: InputMaybe<PostsSectionsButtonsFilter>;
  columns?: InputMaybe<PostsSectionsColumnsFilter>;
  image?: InputMaybe<PostsSectionsImageFilter>;
  quote?: InputMaybe<PostsSectionsQuoteFilter>;
  form?: InputMaybe<PostsSectionsFormFilter>;
  html?: InputMaybe<PostsSectionsHtmlFilter>;
};

export type PostsFilter = {
  title?: InputMaybe<StringFilter>;
  excerpt?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  imageAlt?: InputMaybe<StringFilter>;
  sections?: InputMaybe<PostsSectionsFilter>;
  url?: InputMaybe<StringFilter>;
  date?: InputMaybe<DatetimeFilter>;
  modified?: InputMaybe<DatetimeFilter>;
};

export type PostsConnectionEdges = {
  __typename?: 'PostsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Posts>;
};

export type PostsConnection = Connection & {
  __typename?: 'PostsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PostsConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updatePages: Pages;
  createPages: Pages;
  updatePosts: Posts;
  createPosts: Posts;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdatePagesArgs = {
  relativePath: Scalars['String']['input'];
  params: PagesMutation;
};


export type MutationCreatePagesArgs = {
  relativePath: Scalars['String']['input'];
  params: PagesMutation;
};


export type MutationUpdatePostsArgs = {
  relativePath: Scalars['String']['input'];
  params: PostsMutation;
};


export type MutationCreatePostsArgs = {
  relativePath: Scalars['String']['input'];
  params: PostsMutation;
};

export type DocumentUpdateMutation = {
  pages?: InputMaybe<PagesMutation>;
  posts?: InputMaybe<PostsMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  pages?: InputMaybe<PagesMutation>;
  posts?: InputMaybe<PostsMutation>;
};

export type PagesSectionsProseMutation = {
  body?: InputMaybe<Scalars['String']['input']>;
};

export type PagesSectionsDisclosureMutation = {
  summary?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['String']['input']>;
};

export type PagesSectionsEmbedMutation = {
  src?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  variant?: InputMaybe<Scalars['String']['input']>;
  fallback?: InputMaybe<Scalars['String']['input']>;
};

export type PagesSectionsCardMutation = {
  heading?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  imageAlt?: InputMaybe<Scalars['String']['input']>;
  href?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['String']['input']>;
};

export type PagesSectionsGalleryImagesMutation = {
  src?: InputMaybe<Scalars['String']['input']>;
  alt?: InputMaybe<Scalars['String']['input']>;
};

export type PagesSectionsGalleryMutation = {
  images?: InputMaybe<Array<InputMaybe<PagesSectionsGalleryImagesMutation>>>;
};

export type PagesSectionsProfilesPeopleLinksMutation = {
  href?: InputMaybe<Scalars['String']['input']>;
};

export type PagesSectionsProfilesPeopleMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  role?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['String']['input']>;
  links?: InputMaybe<Array<InputMaybe<PagesSectionsProfilesPeopleLinksMutation>>>;
};

export type PagesSectionsProfilesMutation = {
  people?: InputMaybe<Array<InputMaybe<PagesSectionsProfilesPeopleMutation>>>;
};

export type PagesSectionsVideoMutation = {
  src?: InputMaybe<Scalars['String']['input']>;
  captions?: InputMaybe<Scalars['String']['input']>;
  poster?: InputMaybe<Scalars['String']['input']>;
  caption?: InputMaybe<Scalars['String']['input']>;
};

export type PagesSectionsButtonsButtonsMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  href?: InputMaybe<Scalars['String']['input']>;
  style?: InputMaybe<Scalars['String']['input']>;
  newTab?: InputMaybe<Scalars['Boolean']['input']>;
};

export type PagesSectionsButtonsMutation = {
  buttons?: InputMaybe<Array<InputMaybe<PagesSectionsButtonsButtonsMutation>>>;
};

export type PagesSectionsColumnsColumnsMutation = {
  body?: InputMaybe<Scalars['String']['input']>;
};

export type PagesSectionsColumnsMutation = {
  layout?: InputMaybe<Scalars['String']['input']>;
  columns?: InputMaybe<Array<InputMaybe<PagesSectionsColumnsColumnsMutation>>>;
};

export type PagesSectionsImageMutation = {
  src?: InputMaybe<Scalars['String']['input']>;
  alt?: InputMaybe<Scalars['String']['input']>;
  decorative?: InputMaybe<Scalars['Boolean']['input']>;
  caption?: InputMaybe<Scalars['String']['input']>;
  width?: InputMaybe<Scalars['Float']['input']>;
  height?: InputMaybe<Scalars['Float']['input']>;
};

export type PagesSectionsQuoteMutation = {
  text?: InputMaybe<Scalars['String']['input']>;
  attribution?: InputMaybe<Scalars['String']['input']>;
};

export type PagesSectionsFormFieldsMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  name?: InputMaybe<Scalars['String']['input']>;
  type?: InputMaybe<Scalars['String']['input']>;
  required?: InputMaybe<Scalars['Boolean']['input']>;
  help?: InputMaybe<Scalars['String']['input']>;
};

export type PagesSectionsFormMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  intro?: InputMaybe<Scalars['String']['input']>;
  fields?: InputMaybe<Array<InputMaybe<PagesSectionsFormFieldsMutation>>>;
  consent?: InputMaybe<Scalars['String']['input']>;
  success?: InputMaybe<Scalars['String']['input']>;
  submit?: InputMaybe<Scalars['String']['input']>;
  action?: InputMaybe<Scalars['String']['input']>;
};

export type PagesSectionsHtmlMutation = {
  html?: InputMaybe<Scalars['String']['input']>;
};

export type PagesSectionsMutation = {
  prose?: InputMaybe<PagesSectionsProseMutation>;
  disclosure?: InputMaybe<PagesSectionsDisclosureMutation>;
  embed?: InputMaybe<PagesSectionsEmbedMutation>;
  card?: InputMaybe<PagesSectionsCardMutation>;
  gallery?: InputMaybe<PagesSectionsGalleryMutation>;
  profiles?: InputMaybe<PagesSectionsProfilesMutation>;
  video?: InputMaybe<PagesSectionsVideoMutation>;
  buttons?: InputMaybe<PagesSectionsButtonsMutation>;
  columns?: InputMaybe<PagesSectionsColumnsMutation>;
  image?: InputMaybe<PagesSectionsImageMutation>;
  quote?: InputMaybe<PagesSectionsQuoteMutation>;
  form?: InputMaybe<PagesSectionsFormMutation>;
  html?: InputMaybe<PagesSectionsHtmlMutation>;
};

export type PagesMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  excerpt?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  imageAlt?: InputMaybe<Scalars['String']['input']>;
  sections?: InputMaybe<Array<InputMaybe<PagesSectionsMutation>>>;
  url?: InputMaybe<Scalars['String']['input']>;
  parent?: InputMaybe<Scalars['String']['input']>;
  order?: InputMaybe<Scalars['Float']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  modified?: InputMaybe<Scalars['String']['input']>;
};

export type PostsSectionsProseMutation = {
  body?: InputMaybe<Scalars['String']['input']>;
};

export type PostsSectionsDisclosureMutation = {
  summary?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['String']['input']>;
};

export type PostsSectionsEmbedMutation = {
  src?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  variant?: InputMaybe<Scalars['String']['input']>;
  fallback?: InputMaybe<Scalars['String']['input']>;
};

export type PostsSectionsCardMutation = {
  heading?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  imageAlt?: InputMaybe<Scalars['String']['input']>;
  href?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['String']['input']>;
};

export type PostsSectionsGalleryImagesMutation = {
  src?: InputMaybe<Scalars['String']['input']>;
  alt?: InputMaybe<Scalars['String']['input']>;
};

export type PostsSectionsGalleryMutation = {
  images?: InputMaybe<Array<InputMaybe<PostsSectionsGalleryImagesMutation>>>;
};

export type PostsSectionsProfilesPeopleLinksMutation = {
  href?: InputMaybe<Scalars['String']['input']>;
};

export type PostsSectionsProfilesPeopleMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  role?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['String']['input']>;
  links?: InputMaybe<Array<InputMaybe<PostsSectionsProfilesPeopleLinksMutation>>>;
};

export type PostsSectionsProfilesMutation = {
  people?: InputMaybe<Array<InputMaybe<PostsSectionsProfilesPeopleMutation>>>;
};

export type PostsSectionsVideoMutation = {
  src?: InputMaybe<Scalars['String']['input']>;
  captions?: InputMaybe<Scalars['String']['input']>;
  poster?: InputMaybe<Scalars['String']['input']>;
  caption?: InputMaybe<Scalars['String']['input']>;
};

export type PostsSectionsButtonsButtonsMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  href?: InputMaybe<Scalars['String']['input']>;
  style?: InputMaybe<Scalars['String']['input']>;
  newTab?: InputMaybe<Scalars['Boolean']['input']>;
};

export type PostsSectionsButtonsMutation = {
  buttons?: InputMaybe<Array<InputMaybe<PostsSectionsButtonsButtonsMutation>>>;
};

export type PostsSectionsColumnsColumnsMutation = {
  body?: InputMaybe<Scalars['String']['input']>;
};

export type PostsSectionsColumnsMutation = {
  layout?: InputMaybe<Scalars['String']['input']>;
  columns?: InputMaybe<Array<InputMaybe<PostsSectionsColumnsColumnsMutation>>>;
};

export type PostsSectionsImageMutation = {
  src?: InputMaybe<Scalars['String']['input']>;
  alt?: InputMaybe<Scalars['String']['input']>;
  decorative?: InputMaybe<Scalars['Boolean']['input']>;
  caption?: InputMaybe<Scalars['String']['input']>;
  width?: InputMaybe<Scalars['Float']['input']>;
  height?: InputMaybe<Scalars['Float']['input']>;
};

export type PostsSectionsQuoteMutation = {
  text?: InputMaybe<Scalars['String']['input']>;
  attribution?: InputMaybe<Scalars['String']['input']>;
};

export type PostsSectionsFormFieldsMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  name?: InputMaybe<Scalars['String']['input']>;
  type?: InputMaybe<Scalars['String']['input']>;
  required?: InputMaybe<Scalars['Boolean']['input']>;
  help?: InputMaybe<Scalars['String']['input']>;
};

export type PostsSectionsFormMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  intro?: InputMaybe<Scalars['String']['input']>;
  fields?: InputMaybe<Array<InputMaybe<PostsSectionsFormFieldsMutation>>>;
  consent?: InputMaybe<Scalars['String']['input']>;
  success?: InputMaybe<Scalars['String']['input']>;
  submit?: InputMaybe<Scalars['String']['input']>;
  action?: InputMaybe<Scalars['String']['input']>;
};

export type PostsSectionsHtmlMutation = {
  html?: InputMaybe<Scalars['String']['input']>;
};

export type PostsSectionsMutation = {
  prose?: InputMaybe<PostsSectionsProseMutation>;
  disclosure?: InputMaybe<PostsSectionsDisclosureMutation>;
  embed?: InputMaybe<PostsSectionsEmbedMutation>;
  card?: InputMaybe<PostsSectionsCardMutation>;
  gallery?: InputMaybe<PostsSectionsGalleryMutation>;
  profiles?: InputMaybe<PostsSectionsProfilesMutation>;
  video?: InputMaybe<PostsSectionsVideoMutation>;
  buttons?: InputMaybe<PostsSectionsButtonsMutation>;
  columns?: InputMaybe<PostsSectionsColumnsMutation>;
  image?: InputMaybe<PostsSectionsImageMutation>;
  quote?: InputMaybe<PostsSectionsQuoteMutation>;
  form?: InputMaybe<PostsSectionsFormMutation>;
  html?: InputMaybe<PostsSectionsHtmlMutation>;
};

export type PostsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  excerpt?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  imageAlt?: InputMaybe<Scalars['String']['input']>;
  sections?: InputMaybe<Array<InputMaybe<PostsSectionsMutation>>>;
  url?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  modified?: InputMaybe<Scalars['String']['input']>;
};

export type StringFilter = {
  startsWith?: string | null | undefined;
  eq?: string | null | undefined;
  exists?: boolean | null | undefined;
  in?: Array<string | null | undefined> | null | undefined;
};

export type ImageFilter = {
  startsWith?: string | null | undefined;
  eq?: string | null | undefined;
  exists?: boolean | null | undefined;
  in?: Array<string | null | undefined> | null | undefined;
};

export type PagesSectionsProseFilter = {
  body?: StringFilter | null | undefined;
};

export type PagesSectionsDisclosureFilter = {
  summary?: StringFilter | null | undefined;
  body?: StringFilter | null | undefined;
};

export type PagesSectionsEmbedFilter = {
  src?: StringFilter | null | undefined;
  title?: StringFilter | null | undefined;
  variant?: StringFilter | null | undefined;
  fallback?: StringFilter | null | undefined;
};

export type PagesSectionsCardFilter = {
  heading?: StringFilter | null | undefined;
  image?: ImageFilter | null | undefined;
  imageAlt?: StringFilter | null | undefined;
  href?: StringFilter | null | undefined;
  body?: StringFilter | null | undefined;
};

export type PagesSectionsGalleryImagesFilter = {
  src?: ImageFilter | null | undefined;
  alt?: StringFilter | null | undefined;
};

export type PagesSectionsGalleryFilter = {
  images?: PagesSectionsGalleryImagesFilter | null | undefined;
};

export type PagesSectionsProfilesPeopleLinksFilter = {
  href?: StringFilter | null | undefined;
};

export type PagesSectionsProfilesPeopleFilter = {
  name?: StringFilter | null | undefined;
  role?: StringFilter | null | undefined;
  body?: StringFilter | null | undefined;
  links?: PagesSectionsProfilesPeopleLinksFilter | null | undefined;
};

export type PagesSectionsProfilesFilter = {
  people?: PagesSectionsProfilesPeopleFilter | null | undefined;
};

export type PagesSectionsVideoFilter = {
  src?: ImageFilter | null | undefined;
  captions?: ImageFilter | null | undefined;
  poster?: ImageFilter | null | undefined;
  caption?: StringFilter | null | undefined;
};

export type BooleanFilter = {
  eq?: boolean | null | undefined;
  exists?: boolean | null | undefined;
};

export type PagesSectionsButtonsButtonsFilter = {
  label?: StringFilter | null | undefined;
  href?: StringFilter | null | undefined;
  style?: StringFilter | null | undefined;
  newTab?: BooleanFilter | null | undefined;
};

export type PagesSectionsButtonsFilter = {
  buttons?: PagesSectionsButtonsButtonsFilter | null | undefined;
};

export type PagesSectionsColumnsColumnsFilter = {
  body?: StringFilter | null | undefined;
};

export type PagesSectionsColumnsFilter = {
  layout?: StringFilter | null | undefined;
  columns?: PagesSectionsColumnsColumnsFilter | null | undefined;
};

export type NumberFilter = {
  lt?: number | null | undefined;
  lte?: number | null | undefined;
  gte?: number | null | undefined;
  gt?: number | null | undefined;
  eq?: number | null | undefined;
  exists?: boolean | null | undefined;
  in?: Array<number | null | undefined> | null | undefined;
};

export type PagesSectionsImageFilter = {
  src?: ImageFilter | null | undefined;
  alt?: StringFilter | null | undefined;
  decorative?: BooleanFilter | null | undefined;
  caption?: StringFilter | null | undefined;
  width?: NumberFilter | null | undefined;
  height?: NumberFilter | null | undefined;
};

export type PagesSectionsQuoteFilter = {
  text?: StringFilter | null | undefined;
  attribution?: StringFilter | null | undefined;
};

export type PagesSectionsFormFieldsFilter = {
  label?: StringFilter | null | undefined;
  name?: StringFilter | null | undefined;
  type?: StringFilter | null | undefined;
  required?: BooleanFilter | null | undefined;
  help?: StringFilter | null | undefined;
};

export type PagesSectionsFormFilter = {
  name?: StringFilter | null | undefined;
  intro?: StringFilter | null | undefined;
  fields?: PagesSectionsFormFieldsFilter | null | undefined;
  consent?: StringFilter | null | undefined;
  success?: StringFilter | null | undefined;
  submit?: StringFilter | null | undefined;
  action?: StringFilter | null | undefined;
};

export type PagesSectionsHtmlFilter = {
  html?: StringFilter | null | undefined;
};

export type PagesSectionsFilter = {
  prose?: PagesSectionsProseFilter | null | undefined;
  disclosure?: PagesSectionsDisclosureFilter | null | undefined;
  embed?: PagesSectionsEmbedFilter | null | undefined;
  card?: PagesSectionsCardFilter | null | undefined;
  gallery?: PagesSectionsGalleryFilter | null | undefined;
  profiles?: PagesSectionsProfilesFilter | null | undefined;
  video?: PagesSectionsVideoFilter | null | undefined;
  buttons?: PagesSectionsButtonsFilter | null | undefined;
  columns?: PagesSectionsColumnsFilter | null | undefined;
  image?: PagesSectionsImageFilter | null | undefined;
  quote?: PagesSectionsQuoteFilter | null | undefined;
  form?: PagesSectionsFormFilter | null | undefined;
  html?: PagesSectionsHtmlFilter | null | undefined;
};

export type DatetimeFilter = {
  after?: string | null | undefined;
  before?: string | null | undefined;
  eq?: string | null | undefined;
  exists?: boolean | null | undefined;
  in?: Array<string | null | undefined> | null | undefined;
};

export type PagesFilter = {
  title?: StringFilter | null | undefined;
  excerpt?: StringFilter | null | undefined;
  image?: ImageFilter | null | undefined;
  imageAlt?: StringFilter | null | undefined;
  sections?: PagesSectionsFilter | null | undefined;
  url?: StringFilter | null | undefined;
  parent?: StringFilter | null | undefined;
  order?: NumberFilter | null | undefined;
  date?: DatetimeFilter | null | undefined;
  modified?: DatetimeFilter | null | undefined;
};

export type PostsSectionsProseFilter = {
  body?: StringFilter | null | undefined;
};

export type PostsSectionsDisclosureFilter = {
  summary?: StringFilter | null | undefined;
  body?: StringFilter | null | undefined;
};

export type PostsSectionsEmbedFilter = {
  src?: StringFilter | null | undefined;
  title?: StringFilter | null | undefined;
  variant?: StringFilter | null | undefined;
  fallback?: StringFilter | null | undefined;
};

export type PostsSectionsCardFilter = {
  heading?: StringFilter | null | undefined;
  image?: ImageFilter | null | undefined;
  imageAlt?: StringFilter | null | undefined;
  href?: StringFilter | null | undefined;
  body?: StringFilter | null | undefined;
};

export type PostsSectionsGalleryImagesFilter = {
  src?: ImageFilter | null | undefined;
  alt?: StringFilter | null | undefined;
};

export type PostsSectionsGalleryFilter = {
  images?: PostsSectionsGalleryImagesFilter | null | undefined;
};

export type PostsSectionsProfilesPeopleLinksFilter = {
  href?: StringFilter | null | undefined;
};

export type PostsSectionsProfilesPeopleFilter = {
  name?: StringFilter | null | undefined;
  role?: StringFilter | null | undefined;
  body?: StringFilter | null | undefined;
  links?: PostsSectionsProfilesPeopleLinksFilter | null | undefined;
};

export type PostsSectionsProfilesFilter = {
  people?: PostsSectionsProfilesPeopleFilter | null | undefined;
};

export type PostsSectionsVideoFilter = {
  src?: ImageFilter | null | undefined;
  captions?: ImageFilter | null | undefined;
  poster?: ImageFilter | null | undefined;
  caption?: StringFilter | null | undefined;
};

export type PostsSectionsButtonsButtonsFilter = {
  label?: StringFilter | null | undefined;
  href?: StringFilter | null | undefined;
  style?: StringFilter | null | undefined;
  newTab?: BooleanFilter | null | undefined;
};

export type PostsSectionsButtonsFilter = {
  buttons?: PostsSectionsButtonsButtonsFilter | null | undefined;
};

export type PostsSectionsColumnsColumnsFilter = {
  body?: StringFilter | null | undefined;
};

export type PostsSectionsColumnsFilter = {
  layout?: StringFilter | null | undefined;
  columns?: PostsSectionsColumnsColumnsFilter | null | undefined;
};

export type PostsSectionsImageFilter = {
  src?: ImageFilter | null | undefined;
  alt?: StringFilter | null | undefined;
  decorative?: BooleanFilter | null | undefined;
  caption?: StringFilter | null | undefined;
  width?: NumberFilter | null | undefined;
  height?: NumberFilter | null | undefined;
};

export type PostsSectionsQuoteFilter = {
  text?: StringFilter | null | undefined;
  attribution?: StringFilter | null | undefined;
};

export type PostsSectionsFormFieldsFilter = {
  label?: StringFilter | null | undefined;
  name?: StringFilter | null | undefined;
  type?: StringFilter | null | undefined;
  required?: BooleanFilter | null | undefined;
  help?: StringFilter | null | undefined;
};

export type PostsSectionsFormFilter = {
  name?: StringFilter | null | undefined;
  intro?: StringFilter | null | undefined;
  fields?: PostsSectionsFormFieldsFilter | null | undefined;
  consent?: StringFilter | null | undefined;
  success?: StringFilter | null | undefined;
  submit?: StringFilter | null | undefined;
  action?: StringFilter | null | undefined;
};

export type PostsSectionsHtmlFilter = {
  html?: StringFilter | null | undefined;
};

export type PostsSectionsFilter = {
  prose?: PostsSectionsProseFilter | null | undefined;
  disclosure?: PostsSectionsDisclosureFilter | null | undefined;
  embed?: PostsSectionsEmbedFilter | null | undefined;
  card?: PostsSectionsCardFilter | null | undefined;
  gallery?: PostsSectionsGalleryFilter | null | undefined;
  profiles?: PostsSectionsProfilesFilter | null | undefined;
  video?: PostsSectionsVideoFilter | null | undefined;
  buttons?: PostsSectionsButtonsFilter | null | undefined;
  columns?: PostsSectionsColumnsFilter | null | undefined;
  image?: PostsSectionsImageFilter | null | undefined;
  quote?: PostsSectionsQuoteFilter | null | undefined;
  form?: PostsSectionsFormFilter | null | undefined;
  html?: PostsSectionsHtmlFilter | null | undefined;
};

export type PostsFilter = {
  title?: StringFilter | null | undefined;
  excerpt?: StringFilter | null | undefined;
  image?: ImageFilter | null | undefined;
  imageAlt?: StringFilter | null | undefined;
  sections?: PostsSectionsFilter | null | undefined;
  url?: StringFilter | null | undefined;
  date?: DatetimeFilter | null | undefined;
  modified?: DatetimeFilter | null | undefined;
};

export type PagesPartsFragment = { __typename: 'Pages', title: string | null, excerpt: string | null, image: string | null, imageAlt: string | null, url: string | null, parent: string | null, order: number | null, date: string | null, modified: string | null, sections: Array<
    | { __typename: 'PagesSectionsProse', body: string | null }
    | { __typename: 'PagesSectionsDisclosure', summary: string | null, body: string | null }
    | { __typename: 'PagesSectionsEmbed', src: string | null, title: string | null, variant: string | null, fallback: string | null }
    | { __typename: 'PagesSectionsCard', heading: string | null, image: string | null, imageAlt: string | null, href: string | null, body: string | null }
    | { __typename: 'PagesSectionsGallery', images: Array<{ __typename: 'PagesSectionsGalleryImages', src: string | null, alt: string | null } | null> | null }
    | { __typename: 'PagesSectionsProfiles', people: Array<{ __typename: 'PagesSectionsProfilesPeople', name: string | null, role: string | null, body: string | null, links: Array<{ __typename: 'PagesSectionsProfilesPeopleLinks', href: string | null } | null> | null } | null> | null }
    | { __typename: 'PagesSectionsVideo', src: string | null, captions: string | null, poster: string | null, caption: string | null }
    | { __typename: 'PagesSectionsButtons', buttons: Array<{ __typename: 'PagesSectionsButtonsButtons', label: string | null, href: string | null, style: string | null, newTab: boolean | null } | null> | null }
    | { __typename: 'PagesSectionsColumns', layout: string | null, columns: Array<{ __typename: 'PagesSectionsColumnsColumns', body: string | null } | null> | null }
    | { __typename: 'PagesSectionsImage', src: string | null, alt: string | null, decorative: boolean | null, caption: string | null, width: number | null, height: number | null }
    | { __typename: 'PagesSectionsQuote', text: string | null, attribution: string | null }
    | { __typename: 'PagesSectionsForm', name: string | null, intro: string | null, consent: string | null, success: string | null, submit: string | null, action: string | null, fields: Array<{ __typename: 'PagesSectionsFormFields', label: string | null, name: string | null, type: string | null, required: boolean | null, help: string | null } | null> | null }
    | { __typename: 'PagesSectionsHtml', html: string | null }
   | null> | null };

export type PostsPartsFragment = { __typename: 'Posts', title: string | null, excerpt: string | null, image: string | null, imageAlt: string | null, url: string | null, date: string | null, modified: string | null, sections: Array<
    | { __typename: 'PostsSectionsProse', body: string | null }
    | { __typename: 'PostsSectionsDisclosure', summary: string | null, body: string | null }
    | { __typename: 'PostsSectionsEmbed', src: string | null, title: string | null, variant: string | null, fallback: string | null }
    | { __typename: 'PostsSectionsCard', heading: string | null, image: string | null, imageAlt: string | null, href: string | null, body: string | null }
    | { __typename: 'PostsSectionsGallery', images: Array<{ __typename: 'PostsSectionsGalleryImages', src: string | null, alt: string | null } | null> | null }
    | { __typename: 'PostsSectionsProfiles', people: Array<{ __typename: 'PostsSectionsProfilesPeople', name: string | null, role: string | null, body: string | null, links: Array<{ __typename: 'PostsSectionsProfilesPeopleLinks', href: string | null } | null> | null } | null> | null }
    | { __typename: 'PostsSectionsVideo', src: string | null, captions: string | null, poster: string | null, caption: string | null }
    | { __typename: 'PostsSectionsButtons', buttons: Array<{ __typename: 'PostsSectionsButtonsButtons', label: string | null, href: string | null, style: string | null, newTab: boolean | null } | null> | null }
    | { __typename: 'PostsSectionsColumns', layout: string | null, columns: Array<{ __typename: 'PostsSectionsColumnsColumns', body: string | null } | null> | null }
    | { __typename: 'PostsSectionsImage', src: string | null, alt: string | null, decorative: boolean | null, caption: string | null, width: number | null, height: number | null }
    | { __typename: 'PostsSectionsQuote', text: string | null, attribution: string | null }
    | { __typename: 'PostsSectionsForm', name: string | null, intro: string | null, consent: string | null, success: string | null, submit: string | null, action: string | null, fields: Array<{ __typename: 'PostsSectionsFormFields', label: string | null, name: string | null, type: string | null, required: boolean | null, help: string | null } | null> | null }
    | { __typename: 'PostsSectionsHtml', html: string | null }
   | null> | null };

export type PagesQueryVariables = Exact<{
  relativePath: string;
}>;


export type PagesQuery = { pages: { __typename: 'Pages', id: string, title: string | null, excerpt: string | null, image: string | null, imageAlt: string | null, url: string | null, parent: string | null, order: number | null, date: string | null, modified: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, sections: Array<
      | { __typename: 'PagesSectionsProse', body: string | null }
      | { __typename: 'PagesSectionsDisclosure', summary: string | null, body: string | null }
      | { __typename: 'PagesSectionsEmbed', src: string | null, title: string | null, variant: string | null, fallback: string | null }
      | { __typename: 'PagesSectionsCard', heading: string | null, image: string | null, imageAlt: string | null, href: string | null, body: string | null }
      | { __typename: 'PagesSectionsGallery', images: Array<{ __typename: 'PagesSectionsGalleryImages', src: string | null, alt: string | null } | null> | null }
      | { __typename: 'PagesSectionsProfiles', people: Array<{ __typename: 'PagesSectionsProfilesPeople', name: string | null, role: string | null, body: string | null, links: Array<{ __typename: 'PagesSectionsProfilesPeopleLinks', href: string | null } | null> | null } | null> | null }
      | { __typename: 'PagesSectionsVideo', src: string | null, captions: string | null, poster: string | null, caption: string | null }
      | { __typename: 'PagesSectionsButtons', buttons: Array<{ __typename: 'PagesSectionsButtonsButtons', label: string | null, href: string | null, style: string | null, newTab: boolean | null } | null> | null }
      | { __typename: 'PagesSectionsColumns', layout: string | null, columns: Array<{ __typename: 'PagesSectionsColumnsColumns', body: string | null } | null> | null }
      | { __typename: 'PagesSectionsImage', src: string | null, alt: string | null, decorative: boolean | null, caption: string | null, width: number | null, height: number | null }
      | { __typename: 'PagesSectionsQuote', text: string | null, attribution: string | null }
      | { __typename: 'PagesSectionsForm', name: string | null, intro: string | null, consent: string | null, success: string | null, submit: string | null, action: string | null, fields: Array<{ __typename: 'PagesSectionsFormFields', label: string | null, name: string | null, type: string | null, required: boolean | null, help: string | null } | null> | null }
      | { __typename: 'PagesSectionsHtml', html: string | null }
     | null> | null } };

export type PagesConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: PagesFilter | null | undefined;
}>;


export type PagesConnectionQuery = { pagesConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Pages', id: string, title: string | null, excerpt: string | null, image: string | null, imageAlt: string | null, url: string | null, parent: string | null, order: number | null, date: string | null, modified: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, sections: Array<
          | { __typename: 'PagesSectionsProse', body: string | null }
          | { __typename: 'PagesSectionsDisclosure', summary: string | null, body: string | null }
          | { __typename: 'PagesSectionsEmbed', src: string | null, title: string | null, variant: string | null, fallback: string | null }
          | { __typename: 'PagesSectionsCard', heading: string | null, image: string | null, imageAlt: string | null, href: string | null, body: string | null }
          | { __typename: 'PagesSectionsGallery', images: Array<{ __typename: 'PagesSectionsGalleryImages', src: string | null, alt: string | null } | null> | null }
          | { __typename: 'PagesSectionsProfiles', people: Array<{ __typename: 'PagesSectionsProfilesPeople', name: string | null, role: string | null, body: string | null, links: Array<{ __typename: 'PagesSectionsProfilesPeopleLinks', href: string | null } | null> | null } | null> | null }
          | { __typename: 'PagesSectionsVideo', src: string | null, captions: string | null, poster: string | null, caption: string | null }
          | { __typename: 'PagesSectionsButtons', buttons: Array<{ __typename: 'PagesSectionsButtonsButtons', label: string | null, href: string | null, style: string | null, newTab: boolean | null } | null> | null }
          | { __typename: 'PagesSectionsColumns', layout: string | null, columns: Array<{ __typename: 'PagesSectionsColumnsColumns', body: string | null } | null> | null }
          | { __typename: 'PagesSectionsImage', src: string | null, alt: string | null, decorative: boolean | null, caption: string | null, width: number | null, height: number | null }
          | { __typename: 'PagesSectionsQuote', text: string | null, attribution: string | null }
          | { __typename: 'PagesSectionsForm', name: string | null, intro: string | null, consent: string | null, success: string | null, submit: string | null, action: string | null, fields: Array<{ __typename: 'PagesSectionsFormFields', label: string | null, name: string | null, type: string | null, required: boolean | null, help: string | null } | null> | null }
          | { __typename: 'PagesSectionsHtml', html: string | null }
         | null> | null } | null } | null> | null } };

export type PostsQueryVariables = Exact<{
  relativePath: string;
}>;


export type PostsQuery = { posts: { __typename: 'Posts', id: string, title: string | null, excerpt: string | null, image: string | null, imageAlt: string | null, url: string | null, date: string | null, modified: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, sections: Array<
      | { __typename: 'PostsSectionsProse', body: string | null }
      | { __typename: 'PostsSectionsDisclosure', summary: string | null, body: string | null }
      | { __typename: 'PostsSectionsEmbed', src: string | null, title: string | null, variant: string | null, fallback: string | null }
      | { __typename: 'PostsSectionsCard', heading: string | null, image: string | null, imageAlt: string | null, href: string | null, body: string | null }
      | { __typename: 'PostsSectionsGallery', images: Array<{ __typename: 'PostsSectionsGalleryImages', src: string | null, alt: string | null } | null> | null }
      | { __typename: 'PostsSectionsProfiles', people: Array<{ __typename: 'PostsSectionsProfilesPeople', name: string | null, role: string | null, body: string | null, links: Array<{ __typename: 'PostsSectionsProfilesPeopleLinks', href: string | null } | null> | null } | null> | null }
      | { __typename: 'PostsSectionsVideo', src: string | null, captions: string | null, poster: string | null, caption: string | null }
      | { __typename: 'PostsSectionsButtons', buttons: Array<{ __typename: 'PostsSectionsButtonsButtons', label: string | null, href: string | null, style: string | null, newTab: boolean | null } | null> | null }
      | { __typename: 'PostsSectionsColumns', layout: string | null, columns: Array<{ __typename: 'PostsSectionsColumnsColumns', body: string | null } | null> | null }
      | { __typename: 'PostsSectionsImage', src: string | null, alt: string | null, decorative: boolean | null, caption: string | null, width: number | null, height: number | null }
      | { __typename: 'PostsSectionsQuote', text: string | null, attribution: string | null }
      | { __typename: 'PostsSectionsForm', name: string | null, intro: string | null, consent: string | null, success: string | null, submit: string | null, action: string | null, fields: Array<{ __typename: 'PostsSectionsFormFields', label: string | null, name: string | null, type: string | null, required: boolean | null, help: string | null } | null> | null }
      | { __typename: 'PostsSectionsHtml', html: string | null }
     | null> | null } };

export type PostsConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: PostsFilter | null | undefined;
}>;


export type PostsConnectionQuery = { postsConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Posts', id: string, title: string | null, excerpt: string | null, image: string | null, imageAlt: string | null, url: string | null, date: string | null, modified: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, sections: Array<
          | { __typename: 'PostsSectionsProse', body: string | null }
          | { __typename: 'PostsSectionsDisclosure', summary: string | null, body: string | null }
          | { __typename: 'PostsSectionsEmbed', src: string | null, title: string | null, variant: string | null, fallback: string | null }
          | { __typename: 'PostsSectionsCard', heading: string | null, image: string | null, imageAlt: string | null, href: string | null, body: string | null }
          | { __typename: 'PostsSectionsGallery', images: Array<{ __typename: 'PostsSectionsGalleryImages', src: string | null, alt: string | null } | null> | null }
          | { __typename: 'PostsSectionsProfiles', people: Array<{ __typename: 'PostsSectionsProfilesPeople', name: string | null, role: string | null, body: string | null, links: Array<{ __typename: 'PostsSectionsProfilesPeopleLinks', href: string | null } | null> | null } | null> | null }
          | { __typename: 'PostsSectionsVideo', src: string | null, captions: string | null, poster: string | null, caption: string | null }
          | { __typename: 'PostsSectionsButtons', buttons: Array<{ __typename: 'PostsSectionsButtonsButtons', label: string | null, href: string | null, style: string | null, newTab: boolean | null } | null> | null }
          | { __typename: 'PostsSectionsColumns', layout: string | null, columns: Array<{ __typename: 'PostsSectionsColumnsColumns', body: string | null } | null> | null }
          | { __typename: 'PostsSectionsImage', src: string | null, alt: string | null, decorative: boolean | null, caption: string | null, width: number | null, height: number | null }
          | { __typename: 'PostsSectionsQuote', text: string | null, attribution: string | null }
          | { __typename: 'PostsSectionsForm', name: string | null, intro: string | null, consent: string | null, success: string | null, submit: string | null, action: string | null, fields: Array<{ __typename: 'PostsSectionsFormFields', label: string | null, name: string | null, type: string | null, required: boolean | null, help: string | null } | null> | null }
          | { __typename: 'PostsSectionsHtml', html: string | null }
         | null> | null } | null } | null> | null } };

export const PagesPartsFragmentDoc = gql`
    fragment PagesParts on Pages {
  __typename
  title
  excerpt
  image
  imageAlt
  sections {
    __typename
    ... on PagesSectionsProse {
      body
    }
    ... on PagesSectionsDisclosure {
      summary
      body
    }
    ... on PagesSectionsEmbed {
      src
      title
      variant
      fallback
    }
    ... on PagesSectionsCard {
      heading
      image
      imageAlt
      href
      body
    }
    ... on PagesSectionsGallery {
      images {
        __typename
        src
        alt
      }
    }
    ... on PagesSectionsProfiles {
      people {
        __typename
        name
        role
        body
        links {
          __typename
          href
        }
      }
    }
    ... on PagesSectionsVideo {
      src
      captions
      poster
      caption
    }
    ... on PagesSectionsButtons {
      buttons {
        __typename
        label
        href
        style
        newTab
      }
    }
    ... on PagesSectionsColumns {
      layout
      columns {
        __typename
        body
      }
    }
    ... on PagesSectionsImage {
      src
      alt
      decorative
      caption
      width
      height
    }
    ... on PagesSectionsQuote {
      text
      attribution
    }
    ... on PagesSectionsForm {
      name
      intro
      fields {
        __typename
        label
        name
        type
        required
        help
      }
      consent
      success
      submit
      action
    }
    ... on PagesSectionsHtml {
      html
    }
  }
  url
  parent
  order
  date
  modified
}
    `;
export const PostsPartsFragmentDoc = gql`
    fragment PostsParts on Posts {
  __typename
  title
  excerpt
  image
  imageAlt
  sections {
    __typename
    ... on PostsSectionsProse {
      body
    }
    ... on PostsSectionsDisclosure {
      summary
      body
    }
    ... on PostsSectionsEmbed {
      src
      title
      variant
      fallback
    }
    ... on PostsSectionsCard {
      heading
      image
      imageAlt
      href
      body
    }
    ... on PostsSectionsGallery {
      images {
        __typename
        src
        alt
      }
    }
    ... on PostsSectionsProfiles {
      people {
        __typename
        name
        role
        body
        links {
          __typename
          href
        }
      }
    }
    ... on PostsSectionsVideo {
      src
      captions
      poster
      caption
    }
    ... on PostsSectionsButtons {
      buttons {
        __typename
        label
        href
        style
        newTab
      }
    }
    ... on PostsSectionsColumns {
      layout
      columns {
        __typename
        body
      }
    }
    ... on PostsSectionsImage {
      src
      alt
      decorative
      caption
      width
      height
    }
    ... on PostsSectionsQuote {
      text
      attribution
    }
    ... on PostsSectionsForm {
      name
      intro
      fields {
        __typename
        label
        name
        type
        required
        help
      }
      consent
      success
      submit
      action
    }
    ... on PostsSectionsHtml {
      html
    }
  }
  url
  date
  modified
}
    `;
export const PagesDocument = gql`
    query pages($relativePath: String!) {
  pages(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PagesParts
  }
}
    ${PagesPartsFragmentDoc}`;
export const PagesConnectionDocument = gql`
    query pagesConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PagesFilter) {
  pagesConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PagesParts
      }
    }
  }
}
    ${PagesPartsFragmentDoc}`;
export const PostsDocument = gql`
    query posts($relativePath: String!) {
  posts(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PostsParts
  }
}
    ${PostsPartsFragmentDoc}`;
export const PostsConnectionDocument = gql`
    query postsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PostsFilter) {
  postsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PostsParts
      }
    }
  }
}
    ${PostsPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      pages(variables: PagesQueryVariables, options?: C): Promise<{data: PagesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PagesQueryVariables, query: string}> {
        return requester<{data: PagesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PagesQueryVariables, query: string}, PagesQueryVariables>(PagesDocument, variables, options);
      },
    pagesConnection(variables?: PagesConnectionQueryVariables, options?: C): Promise<{data: PagesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PagesConnectionQueryVariables, query: string}> {
        return requester<{data: PagesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PagesConnectionQueryVariables, query: string}, PagesConnectionQueryVariables>(PagesConnectionDocument, variables, options);
      },
    posts(variables: PostsQueryVariables, options?: C): Promise<{data: PostsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PostsQueryVariables, query: string}> {
        return requester<{data: PostsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PostsQueryVariables, query: string}, PostsQueryVariables>(PostsDocument, variables, options);
      },
    postsConnection(variables?: PostsConnectionQueryVariables, options?: C): Promise<{data: PostsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PostsConnectionQueryVariables, query: string}> {
        return requester<{data: PostsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PostsConnectionQueryVariables, query: string}, PostsConnectionQueryVariables>(PostsConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "https://content.tinajs.io/2.4/content/beec4181-dd4a-41d1-a89f-6257a916f9b8/github/main",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

export type { Exact };

  